version: "3"

services: 
    app:
        build: 
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./voka_ai:/voka_ai
        command: >-
            sh -c "python manage.py runserver 0.0.0.0:8000"